


INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', '/img/1.png', 'Uma saga épica de ficção científica que mistura ação e escolhas narrativas impactantes.', 'A trilogia Mass Effect transporta o jogador para um universo vasto, onde cada decisão molda o destino da galáxia. Com batalhas intensas, personagens memoráveis e um enredo profundo, esta série tornou-se referência em RPGs modernos, equilibrando ação frenética e narrativa envolvente.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', '/img/2.png', 'Uma jornada épica no Velho Oeste, cheia de drama, escolhas e ação imersiva.', 'Red Dead Redemption 2 leva o jogador para o coração do faroeste americano, explorando a queda de uma gangue e a luta por sobrevivência em meio às mudanças do mundo moderno. Gráficos de ponta, enredo cinematográfico e liberdade de exploração definem a experiência.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', '/img/3.png', 'Um RPG de fantasia sombria com narrativa envolvente e vasto mundo aberto.', 'The Witcher 3 é considerado um dos melhores RPGs já criados, combinando exploração em mundo aberto com histórias cativantes e missões ricamente desenvolvidas. A jornada de Geralt de Rívia coloca o jogador diante de dilemas morais complexos e batalhas épicas contra monstros lendários.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', '/img/4.png', 'Um jogo desafiador que combina precisão, reflexos rápidos e narrativa japonesa.', 'Sekiro: Shadows Die Twice mergulha o jogador no Japão feudal, em uma história de honra, vingança e perseverança. Reconhecido por sua dificuldade elevada, o jogo recompensa a habilidade e paciência do jogador, oferecendo combates intensos e momentos inesquecíveis.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', '/img/5.png', 'Uma aventura de samurai que combina ação cinematográfica com mundo aberto.', 'Inspirado em eventos históricos, Ghost of Tsushima coloca o jogador no papel de Jin Sakai, um guerreiro dividido entre a tradição samurai e a necessidade de se adaptar a novas formas de combate. O jogo impressiona por sua beleza artística e sua atmosfera imersiva.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', '/img/6.png', 'Um dos clássicos mais marcantes da história dos videogames.', 'Super Mario World revolucionou os jogos de plataforma com sua jogabilidade fluida, design de fases criativo e introdução de personagens icônicos como Yoshi. Mesmo décadas após seu lançamento, continua sendo uma referência de diversão e inovação.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', '/img/7.png', 'Um metroidvania atmosférico repleto de segredos e desafios.', 'Hollow Knight transporta o jogador para Hallownest, um reino subterrâneo cheio de mistérios, criaturas bizarras e batalhas desafiadoras. Com estilo artístico único e trilha sonora envolvente, tornou-se um marco entre os jogos independentes.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', '/img/8.png', 'Uma experiência emocionante que mistura arte, música e plataforma precisa.', 'Ori and the Blind Forest encanta com sua narrativa tocante, visuais deslumbrantes e jogabilidade fluida. A história de Ori é um convite à superação e à esperança, tornando-se uma das experiências mais marcantes do gênero.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', '/img/9.png', 'Um jogo de plataforma desafiador com visual inspirado em desenhos antigos.', 'Cuphead combina estética retrô dos anos 1930 com jogabilidade extremamente desafiadora. Cada chefe é um espetáculo visual e mecânico, exigindo precisão e estratégia, tornando-o um jogo amado tanto por seu estilo quanto por sua dificuldade.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', '/img/10.png', 'Uma aventura clássica do ouriço azul explorando o tempo e a velocidade.', 'Sonic CD é lembrado por seu sistema inovador de viagens no tempo, permitindo explorar versões passadas e futuras das fases. Com trilha sonora marcante e gameplay veloz, tornou-se um dos títulos mais distintos e queridos da franquia Sonic.');

INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);